# Generated by Django 5.1.4 on 2026-03-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_brand_id_alter_model_name_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_name',
            name='m_img',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
