# Generated by Django 5.1.4 on 2026-03-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_instauser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instauser',
            name='profile_pic_url',
        ),
    ]
