# Generated by Django 5.1.4 on 2026-03-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_instapost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instapost',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
