# Generated by Django 5.1.4 on 2026-03-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_instalike'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
