# Generated by Django 5.1.4 on 2026-03-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_instauser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
