# Generated by Django 5.1.4 on 2026-03-16 05:45

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_instauser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='brand',
            managers=[
                ('everithing', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='is_delete',
            field=models.BooleanField(default=True),
        ),
    ]
