# Generated by Django 5.1.4 on 2026-03-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_brand_managers_brand_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
