name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.13"]

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # 4. Run migrations
      - name: Apply Migrations
        run: |
          python manage.py migrate

      # 5. Run tests
      - name: Run Tests
        run: |
          python manage.py test
